export type ImageQuestion = {
  id: string;
  imageUrl: string;
  question: string;
  options: string[];
  correct: number;
};

export type ImageCategory = {
  id: string;
  name: string;
  emoji: string;
  color: string;
  questions: ImageQuestion[];
};

const W = (filename: string, width = 400) =>
  `/api/img?url=${encodeURIComponent(`https://commons.wikimedia.org/wiki/Special:FilePath/${filename}?width=${width}`)}`;

export const IMAGE_CATEGORIES: ImageCategory[] = [
  // ─────────────────────────────── BAYRAKLAR ───────────────────────────────
  {
    id: "bayraklar",
    name: "Bayraklar",
    emoji: "🏳️",
    color: "#3b82f6",
    questions: [
      { id: "bf1",  imageUrl: "https://flagcdn.com/w320/tr.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Türkiye", "Tunus", "Azerbaycan", "Pakistan"], correct: 0 },
      { id: "bf2",  imageUrl: "https://flagcdn.com/w320/de.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Belçika", "Avusturya", "Almanya", "İsviçre"], correct: 2 },
      { id: "bf3",  imageUrl: "https://flagcdn.com/w320/fr.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Hollanda", "Fransa", "İtalya", "Romanya"], correct: 1 },
      { id: "bf4",  imageUrl: "https://flagcdn.com/w320/jp.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Güney Kore", "Çin", "Japonya", "Vietnam"], correct: 2 },
      { id: "bf5",  imageUrl: "https://flagcdn.com/w320/br.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Brezilya", "Arjantin", "Meksika", "Kolombiya"], correct: 0 },
      { id: "bf6",  imageUrl: "https://flagcdn.com/w320/ca.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Avustralya", "Amerika", "Kanada", "İngiltere"], correct: 2 },
      { id: "bf7",  imageUrl: "https://flagcdn.com/w320/au.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Yeni Zelanda", "Avustralya", "İngiltere", "Fiji"], correct: 1 },
      { id: "bf8",  imageUrl: "https://flagcdn.com/w320/ar.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Uruguay", "Arjantin", "Yunanistan", "El Salvador"], correct: 1 },
      { id: "bf9",  imageUrl: "https://flagcdn.com/w320/pt.png", question: "Bu bayrak hangi ülkeye ait?", options: ["İtalya", "Brezilya", "Portekiz", "İspanya"], correct: 2 },
      { id: "bf10", imageUrl: "https://flagcdn.com/w320/cn.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Vietnam", "Çin", "Kuzey Kore", "Singapur"], correct: 1 },
      { id: "bf11", imageUrl: "https://flagcdn.com/w320/in.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Pakistan", "Bangladeş", "Hindistan", "Sri Lanka"], correct: 2 },
      { id: "bf12", imageUrl: "https://flagcdn.com/w320/za.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Kenya", "Nijerya", "Zimbabve", "Güney Afrika"], correct: 3 },
      { id: "bf13", imageUrl: "https://flagcdn.com/w320/us.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Avustralya", "Amerika Birleşik Devletleri", "Yeni Zelanda", "İngiltere"], correct: 1 },
      { id: "bf14", imageUrl: "https://flagcdn.com/w320/gb.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Avustralya", "Kanada", "Amerika", "Birleşik Krallık"], correct: 3 },
      { id: "bf15", imageUrl: "https://flagcdn.com/w320/it.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Fransa", "İtalya", "İrlanda", "Meksika"], correct: 1 },
      { id: "bf16", imageUrl: "https://flagcdn.com/w320/es.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Portekiz", "Brezilya", "İspanya", "Kolombiya"], correct: 2 },
      { id: "bf17", imageUrl: "https://flagcdn.com/w320/nl.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Rusya", "Fransa", "Hollanda", "Lüksemburg"], correct: 2 },
      { id: "bf18", imageUrl: "https://flagcdn.com/w320/ru.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Sırbistan", "Rusya", "Slovakya", "Slovenya"], correct: 1 },
      { id: "bf19", imageUrl: "https://flagcdn.com/w320/gr.png", question: "Bu bayrak hangi ülkeye ait?", options: ["İsveç", "Yunanistan", "Finlandiya", "İsrail"], correct: 1 },
      { id: "bf20", imageUrl: "https://flagcdn.com/w320/se.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Finlandiya", "Norveç", "Danimarka", "İsveç"], correct: 3 },
      { id: "bf21", imageUrl: "https://flagcdn.com/w320/no.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Danimarka", "İsveç", "Norveç", "İzlanda"], correct: 2 },
      { id: "bf22", imageUrl: "https://flagcdn.com/w320/ch.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Avusturya", "İsviçre", "Danimarka", "Malta"], correct: 1 },
      { id: "bf23", imageUrl: "https://flagcdn.com/w320/mx.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Kolombiya", "İtalya", "Bolivya", "Meksika"], correct: 3 },
      { id: "bf24", imageUrl: "https://flagcdn.com/w320/sa.png", question: "Bu bayrak hangi ülkeye ait?", options: ["İran", "Irak", "Suudi Arabistan", "Kuveyt"], correct: 2 },
      { id: "bf25", imageUrl: "https://flagcdn.com/w320/dk.png", question: "Bu bayrak hangi ülkeye ait?", options: ["İsveç", "Norveç", "Danimarka", "Finlandiya"], correct: 2 },
      { id: "bf26", imageUrl: "https://flagcdn.com/w320/fi.png", question: "Bu bayrak hangi ülkeye ait?", options: ["İsveç", "Finlandiya", "Estonya", "Letonya"], correct: 1 },
      { id: "bf27", imageUrl: "https://flagcdn.com/w320/pl.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Avusturya", "Polonya", "Endonezya", "Monako"], correct: 1 },
      { id: "bf28", imageUrl: "https://flagcdn.com/w320/ua.png", question: "Bu bayrak hangi ülkeye ait?", options: ["İsveç", "Ukrayna", "Slovakya", "Arjantin"], correct: 1 },
      { id: "bf29", imageUrl: "https://flagcdn.com/w320/eg.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Suriye", "Irak", "Yemen", "Mısır"], correct: 3 },
      { id: "bf30", imageUrl: "https://flagcdn.com/w320/id.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Polonya", "Monako", "Endonezya", "Singapur"], correct: 2 },
      { id: "bf31", imageUrl: "https://flagcdn.com/w320/th.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Tayland", "Laos", "Kamboçya", "Myanmar"], correct: 0 },
      { id: "bf32", imageUrl: "https://flagcdn.com/w320/kr.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Japonya", "Çin", "Güney Kore", "Kuzey Kore"], correct: 2 },
      { id: "bf33", imageUrl: "https://flagcdn.com/w320/nz.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Avustralya", "Fidji", "Yeni Zelanda", "Samoa"], correct: 2 },
      { id: "bf34", imageUrl: "https://flagcdn.com/w320/ng.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Kenya", "Fildişi Sahili", "Gana", "Nijerya"], correct: 3 },
      { id: "bf35", imageUrl: "https://flagcdn.com/w320/pk.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Türkiye", "Pakistan", "Malezya", "Suudi Arabistan"], correct: 1 },
      { id: "bf36", imageUrl: "https://flagcdn.com/w320/ae.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Katar", "Kuveyt", "Bahreyn", "Birleşik Arap Emirlikleri"], correct: 3 },
      { id: "bf37", imageUrl: "https://flagcdn.com/w320/be.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Almanya", "Hollanda", "Belçika", "Lüksemburg"], correct: 2 },
      { id: "bf38", imageUrl: "https://flagcdn.com/w320/at.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Polonya", "Avusturya", "Letonya", "Danimarka"], correct: 1 },
      { id: "bf39", imageUrl: "https://flagcdn.com/w320/ro.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Moldova", "Romanya", "Bulgaristan", "Çad"], correct: 1 },
      { id: "bf40", imageUrl: "https://flagcdn.com/w320/hu.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Avusturya", "Slovakya", "Macaristan", "Çekya"], correct: 2 },
      { id: "bf41", imageUrl: "https://flagcdn.com/w320/cz.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Slovakya", "Çekya", "Polonya", "Slovenya"], correct: 1 },
      { id: "bf42", imageUrl: "https://flagcdn.com/w320/hr.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Sırbistan", "Slovenya", "Bosna Hersek", "Hırvatistan"], correct: 3 },
      { id: "bf43", imageUrl: "https://flagcdn.com/w320/ie.png", question: "Bu bayrak hangi ülkeye ait?", options: ["İtalya", "Meksika", "Fildişi Sahili", "İrlanda"], correct: 3 },
      { id: "bf44", imageUrl: "https://flagcdn.com/w320/il.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Yunanistan", "İsrail", "İsveç", "Finlandiya"], correct: 1 },
      { id: "bf45", imageUrl: "https://flagcdn.com/w320/sg.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Malezya", "Singapur", "Tayvan", "Endonezya"], correct: 1 },
      { id: "bf46", imageUrl: "https://flagcdn.com/w320/my.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Endonezya", "Filipinler", "Malezya", "Tayland"], correct: 2 },
      { id: "bf47", imageUrl: "https://flagcdn.com/w320/cl.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Porto Riko", "Şili", "Küba", "Peru"], correct: 1 },
      { id: "bf48", imageUrl: "https://flagcdn.com/w320/co.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Ekvador", "Venezuela", "Kolombiya", "Bolivya"], correct: 2 },
      { id: "bf49", imageUrl: "https://flagcdn.com/w320/ma.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Libya", "Cezayir", "Fas", "Tunus"], correct: 2 },
      { id: "bf50", imageUrl: "https://flagcdn.com/w320/ke.png", question: "Bu bayrak hangi ülkeye ait?", options: ["Tanzanya", "Uganda", "Kenya", "Etiyopya"], correct: 2 },
    ],
  },

  // ─────────────────────────────── MARKALAR ────────────────────────────────
  {
    id: "markalar",
    name: "Markalar",
    emoji: "🏢",
    color: "#f59e0b",
    questions: [
      { id: "mk1",  imageUrl: W("Apple_logo_black.svg"), question: "Bu logo hangi markaya ait?", options: ["Samsung", "Apple", "Google", "Microsoft"], correct: 1 },
      { id: "mk2",  imageUrl: W("Google_2015_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Yahoo", "Google", "Bing", "Mozilla"], correct: 1 },
      { id: "mk3",  imageUrl: W("Logo_NIKE.svg"), question: "Bu logo hangi markaya ait?", options: ["Adidas", "Puma", "Nike", "Reebok"], correct: 2 },
      { id: "mk4",  imageUrl: W("Adidas_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Adidas", "Nike", "Under Armour", "New Balance"], correct: 0 },
      { id: "mk5",  imageUrl: W("McDonald%27s_Golden_Arches.svg"), question: "Bu logo hangi markaya ait?", options: ["Burger King", "KFC", "McDonald's", "Subway"], correct: 2 },
      { id: "mk6",  imageUrl: W("Coca-Cola_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Pepsi", "Fanta", "Coca-Cola", "Sprite"], correct: 2 },
      { id: "mk7",  imageUrl: W("Netflix_2015_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["HBO", "Disney+", "Amazon Prime", "Netflix"], correct: 3 },
      { id: "mk8",  imageUrl: W("BMW.svg"), question: "Bu logo hangi markaya ait?", options: ["Audi", "Mercedes", "BMW", "Volkswagen"], correct: 2 },
      { id: "mk9",  imageUrl: W("Mercedes-Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["BMW", "Mercedes-Benz", "Audi", "Porsche"], correct: 1 },
      { id: "mk10", imageUrl: W("YouTube_Logo_2017.svg"), question: "Bu logo hangi markaya ait?", options: ["Twitch", "TikTok", "YouTube", "Vimeo"], correct: 2 },
      { id: "mk11", imageUrl: W("Amazon_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["eBay", "Amazon", "Alibaba", "Temu"], correct: 1 },
      { id: "mk12", imageUrl: W("Spotify_logo_without_text.svg"), question: "Bu logo hangi markaya ait?", options: ["Apple Music", "Deezer", "Tidal", "Spotify"], correct: 3 },
      { id: "mk13", imageUrl: W("Samsung_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["LG", "Huawei", "Samsung", "Sony"], correct: 2 },
      { id: "mk14", imageUrl: W("Microsoft_logo_%282012%29.svg"), question: "Bu logo hangi markaya ait?", options: ["Apple", "Google", "Microsoft", "IBM"], correct: 2 },
      { id: "mk15", imageUrl: W("Facebook_f_logo_%282021%29.svg"), question: "Bu logo hangi markaya ait?", options: ["Twitter", "Instagram", "Facebook", "LinkedIn"], correct: 2 },
      { id: "mk16", imageUrl: W("Instagram_logo_2016.svg"), question: "Bu logo hangi markaya ait?", options: ["Snapchat", "Pinterest", "TikTok", "Instagram"], correct: 3 },
      { id: "mk17", imageUrl: W("Toyota_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Honda", "Nissan", "Hyundai", "Toyota"], correct: 3 },
      { id: "mk18", imageUrl: W("Volkswagen_logo_2019.svg"), question: "Bu logo hangi markaya ait?", options: ["Volvo", "Audi", "Volkswagen", "Skoda"], correct: 2 },
      { id: "mk19", imageUrl: W("PlayStation_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Xbox", "Nintendo", "Steam", "PlayStation"], correct: 3 },
      { id: "mk20", imageUrl: W("WhatsApp.svg"), question: "Bu logo hangi markaya ait?", options: ["Telegram", "Signal", "WhatsApp", "Viber"], correct: 2 },
      { id: "mk21", imageUrl: W("Pepsi_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Coca-Cola", "Fanta", "Sprite", "Pepsi"], correct: 3 },
      { id: "mk22", imageUrl: W("X_logo_2023.svg"), question: "Bu logo hangi markaya ait?", options: ["Reddit", "Twitter/X", "Discord", "Tumblr"], correct: 1 },
      { id: "mk23", imageUrl: W("Audi-Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["BMW", "Mercedes", "Audi", "Porsche"], correct: 2 },
      { id: "mk24", imageUrl: W("IKEA_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["H&M", "Zara", "IKEA", "Carrefour"], correct: 2 },
      { id: "mk25", imageUrl: W("PayPal.svg"), question: "Bu logo hangi markaya ait?", options: ["Visa", "Mastercard", "PayPal", "Stripe"], correct: 2 },
      { id: "mk26", imageUrl: W("Ferrari_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Lamborghini", "Maserati", "Ferrari", "Bugatti"], correct: 2 },
      { id: "mk27", imageUrl: W("Lamborghini_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Ferrari", "Lamborghini", "Bugatti", "McLaren"], correct: 1 },
      { id: "mk28", imageUrl: W("Porsche_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["BMW", "Audi", "Mercedes", "Porsche"], correct: 3 },
      { id: "mk29", imageUrl: W("Intel-logo.svg"), question: "Bu logo hangi markaya ait?", options: ["AMD", "NVIDIA", "Intel", "Qualcomm"], correct: 2 },
      { id: "mk30", imageUrl: W("NVIDIA_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Intel", "AMD", "Qualcomm", "NVIDIA"], correct: 3 },
      { id: "mk31", imageUrl: W("Mastercard-logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Visa", "Mastercard", "PayPal", "American Express"], correct: 1 },
      { id: "mk32", imageUrl: W("Visa_Inc._logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Visa", "Mastercard", "UnionPay", "Discover"], correct: 0 },
      { id: "mk33", imageUrl: W("Starbucks_Coffee_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Costa Coffee", "Starbucks", "Tim Hortons", "Dunkin'"], correct: 1 },
      { id: "mk34", imageUrl: W("Honda_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Toyota", "Honda", "Nissan", "Mazda"], correct: 1 },
      { id: "mk35", imageUrl: W("Hyundai_Motor_Company_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Kia", "Hyundai", "Daewoo", "Samsung Motors"], correct: 1 },
      { id: "mk36", imageUrl: W("Puma_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Nike", "Adidas", "Puma", "Reebok"], correct: 2 },
      { id: "mk37", imageUrl: W("Shell_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["BP", "Shell", "Total", "Esso"], correct: 1 },
      { id: "mk38", imageUrl: W("Lego_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Playmobil", "Fisher-Price", "Lego", "Hasbro"], correct: 2 },
      { id: "mk39", imageUrl: W("Disney_wordmark.svg"), question: "Bu logo hangi markaya ait?", options: ["DreamWorks", "Pixar", "Disney", "Universal"], correct: 2 },
      { id: "mk40", imageUrl: W("Red_Bull_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Monster Energy", "Burn", "Red Bull", "Rockstar"], correct: 2 },
      { id: "mk41", imageUrl: W("Zara_Logo.svg"), question: "Bu logo hangi markaya ait?", options: ["H&M", "Zara", "Mango", "Bershka"], correct: 1 },
      { id: "mk42", imageUrl: W("Gucci_logo.svg"), question: "Bu logo hangi markaya ait?", options: ["Louis Vuitton", "Prada", "Gucci", "Chanel"], correct: 2 },
    ],
  },

  // ────────────────────────────── ÜNLÜ YERLER ──────────────────────────────
  {
    id: "yerler",
    name: "Ünlü Yerler",
    emoji: "🏛️",
    color: "#10b981",
    questions: [
      { id: "yr1",  imageUrl: W("Tour_Eiffel_Wikimedia_Commons.jpg"), question: "Bu ünlü yapı nedir?", options: ["Londra Kulesi", "Eyfel Kulesi", "Big Ben", "Burj Khalifa"], correct: 1 },
      { id: "yr2",  imageUrl: W("Colosseo_2020.jpg"), question: "Bu ünlü yapı nedir?", options: ["Atina Agorası", "Koloseum", "Parthenon", "Forum Romanum"], correct: 1 },
      { id: "yr3",  imageUrl: W("Taj_Mahal%2C_Agra%2C_India_edit3.jpg"), question: "Bu ünlü yapı nedir?", options: ["Humayun Türbesi", "Kızıl Kale", "Tac Mahal", "Lotus Tapınağı"], correct: 2 },
      { id: "yr4",  imageUrl: W("Kheops-Pyramid.jpg"), question: "Bu ünlü yapı nedir?", options: ["Sümer Zigguratı", "Maya Piramidi", "Mısır Piramitleri", "Aztec Piramidi"], correct: 2 },
      { id: "yr5",  imageUrl: W("Burjkhalifa.jpg"), question: "Bu ünlü yapı nedir?", options: ["Shanghai Kulesi", "Taipei 101", "Burj Khalifa", "CN Tower"], correct: 2 },
      { id: "yr6",  imageUrl: W("Machu_Picchu%2C_Peru.jpg"), question: "Bu ünlü yer neresidir?", options: ["Chichen Itza", "Tikal", "Machu Picchu", "Nazca"], correct: 2 },
      { id: "yr7",  imageUrl: W("The_Parthenon_in_Athens.jpg"), question: "Bu ünlü yapı nedir?", options: ["Koloseum", "Parthenon", "Pantheon", "Akropol"], correct: 1 },
      { id: "yr8",  imageUrl: W("Leaning_Tower_of_Pisa_%28rectified%29.jpg"), question: "Bu ünlü yapı nedir?", options: ["Pisa Kulesi", "Big Ben", "Eyfel Kulesi", "Aziz Basil Kilisesi"], correct: 0 },
      { id: "yr9",  imageUrl: W("Statue_of_Liberty_7.jpg"), question: "Bu ünlü heykel nedir?", options: ["Rio Heykeli", "Özgürlük Heykeli", "Büyük Sfenks", "Musa Heykeli"], correct: 1 },
      { id: "yr10", imageUrl: W("20090529_great_wall_8218.jpg"), question: "Bu ünlü yapı nedir?", options: ["Çin Seddi", "Hadrian Duvarı", "Berlin Duvarı", "Angkor Wat"], correct: 0 },
      { id: "yr11", imageUrl: W("Sagrada_Familia_01.jpg"), question: "Bu ünlü yapı nedir?", options: ["Notre Dame", "Sagrada Familia", "Westminster Bazilikası", "Köln Katedrali"], correct: 1 },
      { id: "yr12", imageUrl: W("Hagia_Sophia.jpg"), question: "Bu ünlü yapı nedir?", options: ["Sultanahmet Camii", "Topkapı Sarayı", "Ayasofya", "Dolmabahçe"], correct: 2 },
      { id: "yr13", imageUrl: W("Big_Ben.jpg"), question: "Bu ünlü yapı nedir?", options: ["Eyfel Kulesi", "Pisa Kulesi", "Big Ben", "Burj Khalifa"], correct: 2 },
      { id: "yr14", imageUrl: W("Angkor_Wat_sunrise.jpg"), question: "Bu ünlü tapınak nedir?", options: ["Borobudur", "Angkor Wat", "Bagan Tapınağı", "Prambanan"], correct: 1 },
      { id: "yr15", imageUrl: W("Sydney_Opera_House_Sails.jpg"), question: "Bu ünlü yapı nedir?", options: ["Melbourne Arenası", "Auckland Kulesi", "Sydney Opera Binası", "Perth Katedrali"], correct: 2 },
      { id: "yr16", imageUrl: W("Stonehenge2007_07_30.jpg"), question: "Bu ünlü yer neresidir?", options: ["Carnac Taşları", "Easter Island", "Stonehenge", "Avebury"], correct: 2 },
      { id: "yr17", imageUrl: W("Mount_Fuji_2.jpg"), question: "Bu ünlü dağ hangisidir?", options: ["Kilimanjaro", "Mont Blanc", "Fujiyama", "Etna"], correct: 2 },
      { id: "yr18", imageUrl: W("Niagara_Falls.jpg"), question: "Bu ünlü doğal oluşum nedir?", options: ["Victoria Şelalesi", "Angel Şelalesi", "Niagara Şelalesi", "Iguazu Şelalesi"], correct: 2 },
      { id: "yr19", imageUrl: W("Neuschwanstein_Castle.jpg"), question: "Bu ünlü kale neredededir?", options: ["İsviçre", "Avusturya", "Almanya", "Fransa"], correct: 2 },
      { id: "yr20", imageUrl: W("Petra_Jordan_BW_21.JPG"), question: "Bu ünlü arkeolojik alan neresidir?", options: ["Palmira", "Balbek", "Petra", "Jerash"], correct: 2 },
      { id: "yr21", imageUrl: W("Chichen_Itza_3.jpg"), question: "Bu ünlü yapı nedir?", options: ["Machu Picchu", "Teotihuacan", "Chichen Itza", "Palenque"], correct: 2 },
      { id: "yr22", imageUrl: W("Tower_Bridge_from_the_Monument.jpg"), question: "Bu ünlü köprü nedir?", options: ["Westminster Köprüsü", "London Bridge", "Tower Bridge", "Millennium Bridge"], correct: 2 },
      { id: "yr23", imageUrl: W("Buckingham_Palace.jpg"), question: "Bu ünlü saray nedir?", options: ["Windsor Şatosu", "Buckingham Sarayı", "Kensington Sarayı", "St. James Sarayı"], correct: 1 },
      { id: "yr24", imageUrl: W("Grand_Canyon_skywalk.jpg"), question: "Bu ünlü doğal oluşum nedir?", options: ["Büyük Set Resifi", "Grand Canyon", "Bryce Canyon", "Zion Canyon"], correct: 1 },
      { id: "yr25", imageUrl: W("Mount_Everest_as_seen_from_Drukair2_PLW_edit.jpg"), question: "Bu dağ hangisidir?", options: ["K2", "Kangchenjunga", "Everest", "Lhotse"], correct: 2 },
      { id: "yr26", imageUrl: W("Victoria_Falls_-_Zimbabwe_%28August_2009%29.jpg"), question: "Bu ünlü şelale nedir?", options: ["Niagara Şelalesi", "Angel Şelalesi", "Victoria Şelalesi", "Iguazu Şelalesi"], correct: 2 },
      { id: "yr27", imageUrl: W("Alhambra_night_panorama.jpg"), question: "Bu ünlü saray nedir?", options: ["Topkapı", "Escorial", "Alhambra", "Alcazar"], correct: 2 },
      { id: "yr28", imageUrl: W("Colosseum_in_Rome-April_2007-1-_copie_2B.jpg"), question: "Koloseum hangi şehirdedir?", options: ["Atina", "İstanbul", "Paris", "Roma"], correct: 3 },
      { id: "yr29", imageUrl: W("Eiffelturm_Paris.jpg"), question: "Eyfel Kulesi hangi şehirdedir?", options: ["Londra", "Berlin", "Paris", "Madrid"], correct: 2 },
      { id: "yr30", imageUrl: W("Kheops-Pyramid.jpg"), question: "Mısır Piramitleri hangi şehir yakınındadır?", options: ["Kahire/Gize", "Luksor", "İskenderiye", "Asvan"], correct: 0 },
      { id: "yr31", imageUrl: W("Machu_Picchu%2C_Peru.jpg"), question: "Machu Picchu hangi ülkededir?", options: ["Bolivya", "Ekvador", "Peru", "Kolombiya"], correct: 2 },
      { id: "yr32", imageUrl: W("Hagia_Sophia.jpg"), question: "Ayasofya hangi şehirdedir?", options: ["Ankara", "Bursa", "İzmir", "İstanbul"], correct: 3 },
      { id: "yr33", imageUrl: W("Sagrada_Familia_01.jpg"), question: "Sagrada Familia hangi şehirdedir?", options: ["Madrid", "Barselona", "Valencia", "Sevilla"], correct: 1 },
      { id: "yr34", imageUrl: W("Taj_Mahal%2C_Agra%2C_India_edit3.jpg"), question: "Tac Mahal hangi şehirdedir?", options: ["Mumbai", "Delhi", "Agra", "Jaipur"], correct: 2 },
      { id: "yr35", imageUrl: W("Big_Ben.jpg"), question: "Big Ben hangi şehirdedir?", options: ["Dublin", "Edinburgh", "Manchester", "Londra"], correct: 3 },
      { id: "yr36", imageUrl: W("Sydney_Opera_House_Sails.jpg"), question: "Sydney Opera Binası hangi ülkededir?", options: ["Yeni Zelanda", "Güney Afrika", "Avustralya", "Kanada"], correct: 2 },
      { id: "yr37", imageUrl: W("Statue_of_Liberty_7.jpg"), question: "Özgürlük Heykeli hangi şehirdedir?", options: ["Washington D.C.", "Los Angeles", "Chicago", "New York"], correct: 3 },
      { id: "yr38", imageUrl: W("Angkor_Wat_sunrise.jpg"), question: "Angkor Wat hangi ülkededir?", options: ["Tayland", "Vietnam", "Kamboçya", "Laos"], correct: 2 },
      { id: "yr39", imageUrl: W("Stonehenge2007_07_30.jpg"), question: "Stonehenge hangi ülkededir?", options: ["Fransa", "İrlanda", "İskoçya", "İngiltere"], correct: 3 },
      { id: "yr40", imageUrl: W("Burjkhalifa.jpg"), question: "Burj Khalifa hangi şehirdedir?", options: ["Riyad", "Abu Dabi", "Dubai", "Doha"], correct: 2 },
    ],
  },

  // ─────────────────────────────── HAYVANLAR ───────────────────────────────
  {
    id: "hayvanlar",
    name: "Hayvanlar",
    emoji: "🐾",
    color: "#84cc16",
    questions: [
      { id: "hy1",  imageUrl: W("Lion_waiting_in_Namibia.jpg"), question: "Bu hayvan nedir?", options: ["Leopar", "Çita", "Aslan", "Kaplan"], correct: 2 },
      { id: "hy2",  imageUrl: W("African_Bush_Elephant.jpg"), question: "Bu hayvan nedir?", options: ["Gergedan", "Hipopotam", "Fil", "Tapir"], correct: 2 },
      { id: "hy3",  imageUrl: W("YellowLabradorLooking_new.jpg"), question: "Bu köpek ırkı nedir?", options: ["Altın Retriever", "Labrador Retriever", "Beagle", "Husky"], correct: 1 },
      { id: "hy4",  imageUrl: W("Bottlenose_Dolphin_KSC04pd0178.jpg"), question: "Bu deniz canlısı nedir?", options: ["Balina", "Köpek Balığı", "Yunus", "Foklar"], correct: 2 },
      { id: "hy5",  imageUrl: W("Panthera_tigris_sumatran_subspecies.jpg"), question: "Bu hayvan nedir?", options: ["Jaguar", "Leopar", "Aslan", "Kaplan"], correct: 3 },
      { id: "hy6",  imageUrl: W("Grosser_Panda.JPG"), question: "Bu hayvan nedir?", options: ["Kuzey Ayısı", "Koala", "Dev Panda", "Kırmızı Panda"], correct: 2 },
      { id: "hy7",  imageUrl: W("Bald_Eagle_Portrait.jpg"), question: "Bu kuş nedir?", options: ["Şahin", "Kartal", "Akbaba", "Martı"], correct: 1 },
      { id: "hy8",  imageUrl: W("Crocodylus_acutus.jpg"), question: "Bu sürüngen nedir?", options: ["Kertenkele", "Timsah", "Iguana", "Monitör Kertenkele"], correct: 1 },
      { id: "hy9",  imageUrl: W("Giraffe_standing.jpg"), question: "Bu hayvan nedir?", options: ["Deve", "Zürafa", "Fil", "At"], correct: 1 },
      { id: "hy10", imageUrl: W("Camponotus_flavomarginatus_ant.jpg"), question: "Bu böcek nedir?", options: ["Arı", "Karınca", "Termit", "Bit"], correct: 1 },
      { id: "hy11", imageUrl: W("Cheetah_Kruger.jpg"), question: "Bu hayvan nedir?", options: ["Leopar", "Çita", "Aslan", "Jaguar"], correct: 1 },
      { id: "hy12", imageUrl: W("Polar_Bear.jpg"), question: "Bu hayvan nedir?", options: ["Kutup Ayısı", "Kodiak Ayısı", "Boz Ayı", "Panda"], correct: 0 },
      { id: "hy13", imageUrl: W("Flamingo.jpg"), question: "Bu kuş nedir?", options: ["Pelikan", "İbis", "Flamingo", "Turna"], correct: 2 },
      { id: "hy14", imageUrl: W("Gorilla_gorilla_gorilla01.jpg"), question: "Bu hayvan nedir?", options: ["Şempanze", "Orangutan", "Goril", "Bonobo"], correct: 2 },
      { id: "hy15", imageUrl: W("Emperor_Penguin_Manchot_empereur.jpg"), question: "Bu kuş nedir?", options: ["Auklar", "Deniz Papağanı", "İmparator Penguen", "Afrika Pengueni"], correct: 2 },
      { id: "hy16", imageUrl: W("White_shark.jpg"), question: "Bu deniz canlısı nedir?", options: ["Köpek Balığı", "Balina", "Katil Balina", "Büyük Beyaz Köpek Balığı"], correct: 3 },
      { id: "hy17", imageUrl: W("Zebra_Botswana_edit02.jpg"), question: "Bu hayvan nedir?", options: ["At", "Katır", "Zebra", "Eşek"], correct: 2 },
      { id: "hy18", imageUrl: W("Koala_climbing_tree.jpg"), question: "Bu hayvan nedir?", options: ["Opossum", "Keseli Sıçan", "Koala", "Wombat"], correct: 2 },
      { id: "hy19", imageUrl: W("Kangaroo.jpg"), question: "Bu hayvan nedir?", options: ["Wallaby", "Vombat", "Kanguru", "Dingo"], correct: 2 },
      { id: "hy20", imageUrl: W("Peacock_Plumage.jpg"), question: "Bu kuş nedir?", options: ["Tavus Kuşu", "Turna", "Sülün", "Papağan"], correct: 0 },
      { id: "hy21", imageUrl: W("White_rhinoceros.jpg"), question: "Bu hayvan nedir?", options: ["Gergedan", "Hipopotam", "Tapir", "Manda"], correct: 0 },
      { id: "hy22", imageUrl: W("Macaca_nigra_self-portrait_large.jpg"), question: "Bu hayvan nedir?", options: ["Şempanze", "Maymun", "Goril", "Lemur"], correct: 1 },
      { id: "hy23", imageUrl: W("Bubo_bubo_portrait_Luc_Viatour.jpg"), question: "Bu kuş nedir?", options: ["Kartal", "Baykuş", "Akbaba", "Şahin"], correct: 1 },
      { id: "hy24", imageUrl: W("Octopus_vulgaris_2.jpg"), question: "Bu deniz canlısı nedir?", options: ["Kalamar", "Ahtapot", "Mürekkep Balığı", "Denizanası"], correct: 1 },
      { id: "hy25", imageUrl: W("Red_fox_-_British_Wildlife_Centre_%287315946946%29.jpg"), question: "Bu hayvan nedir?", options: ["Kurt", "Çakal", "Tilki", "Rakun"], correct: 2 },
      { id: "hy26", imageUrl: W("Monarch_Butterfly_Danaus_plexippus.jpg"), question: "Bu böcek nedir?", options: ["Güve", "Uğur Böceği", "Kelebek", "Arı"], correct: 2 },
      { id: "hy27", imageUrl: W("Hippocampus_comes2.jpg"), question: "Bu deniz canlısı nedir?", options: ["Denizanası", "Yılan Balığı", "Denizatı", "Denizhıyarı"], correct: 2 },
      { id: "hy28", imageUrl: W("Furcifer_pardalis_-_Nosy_Be_11.jpg"), question: "Bu sürüngen nedir?", options: ["Iguana", "Bukalemun", "Gecko", "Skink"], correct: 1 },
      { id: "hy29", imageUrl: W("Apis_mellifera_Western_honey_bee.jpg"), question: "Bu böcek nedir?", options: ["Yaban Arısı", "Bumblebee", "Bal Arısı", "Eşekarısı"], correct: 2 },
      { id: "hy30", imageUrl: W("Proboscis_Monkey_%28Nasalis_larvatus%29.jpg"), question: "Bu maymun türü nedir?", options: ["Orangutan", "Makak", "Hortumlu Maymun", "Gibbon"], correct: 2 },
      { id: "hy31", imageUrl: W("Snow_Leopard_Seattle_Zoo.jpg"), question: "Bu büyük kedi nedir?", options: ["Kaplan", "Leopar", "Kar Leoparı", "Jaguar"], correct: 2 },
      { id: "hy32", imageUrl: W("Bison_bonasus_frontalis.jpg"), question: "Bu hayvan nedir?", options: ["Bizon", "Manda", "İnek", "Yak"], correct: 0 },
      { id: "hy33", imageUrl: W("African_penguins_Boulders_beach_edit.jpg"), question: "Bu penguenler nerededir?", options: ["Antarktika", "Arjantin", "Güney Afrika", "Yeni Zelanda"], correct: 2 },
      { id: "hy34", imageUrl: W("Pygmy_three-toed_sloth.jpg"), question: "Bu hayvan nedir?", options: ["Ayı", "Tembel Hayvan", "Rakun", "Keseli Sıçan"], correct: 1 },
      { id: "hy35", imageUrl: W("Humpback_whales_in_singing_position.jpg"), question: "Bu deniz memelisi nedir?", options: ["Yunus", "Dev Balina", "Kambur Balina", "Mavi Balina"], correct: 2 },
    ],
  },

  // ────────────────────────────── FUTBOLCULAR ──────────────────────────────
  {
    id: "futbolcular",
    name: "Futbolcular",
    emoji: "⚽",
    color: "#06b6d4",
    questions: [
      { id: "ft1",  imageUrl: W("Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg"), question: "Bu futbolcu kimdir?", options: ["Neymar", "Ronaldo", "Lionel Messi", "Mbappe"], correct: 2 },
      { id: "ft2",  imageUrl: W("Cristiano_Ronaldo_2018.jpg"), question: "Bu futbolcu kimdir?", options: ["Messi", "Cristiano Ronaldo", "Benzema", "Ibrahimovic"], correct: 1 },
      { id: "ft3",  imageUrl: W("Mohamed_Salah_2018.jpg"), question: "Bu futbolcu kimdir?", options: ["Sadio Mane", "Mohamed Salah", "Riyad Mahrez", "Aubameyang"], correct: 1 },
      { id: "ft4",  imageUrl: W("Luka_Modri%C4%87_2019_%28cropped%29.jpg"), question: "Bu futbolcu kimdir?", options: ["Rakitic", "Perisic", "Luka Modric", "Kovacic"], correct: 2 },
      { id: "ft5",  imageUrl: W("Kevin_De_Bruyne.jpg"), question: "Bu futbolcu kimdir?", options: ["Hazard", "Kevin De Bruyne", "Chadli", "Lukaku"], correct: 1 },
      { id: "ft6",  imageUrl: W("Kylian_Mbapp%C3%A9_2018.jpg"), question: "Bu futbolcu kimdir?", options: ["Ousmane Dembele", "Kylian Mbappe", "Antoine Griezmann", "Olivier Giroud"], correct: 1 },
      { id: "ft7",  imageUrl: W("Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg"), question: "Bu futbolcu kaç kez Ballon d'Or kazandı?", options: ["6", "7", "8", "5"], correct: 2 },
      { id: "ft8",  imageUrl: W("Cristiano_Ronaldo_2018.jpg"), question: "Bu futbolcunun milliyeti nedir?", options: ["İspanyol", "Brezilya", "Portekizli", "Arjantin"], correct: 2 },
      { id: "ft9",  imageUrl: W("Mohamed_Salah_2018.jpg"), question: "Bu futbolcu hangi takımda oynar?", options: ["Arsenal", "Chelsea", "Liverpool", "Manchester City"], correct: 2 },
      { id: "ft10", imageUrl: W("Kevin_De_Bruyne.jpg"), question: "Bu futbolcunun milliyeti nedir?", options: ["Hollandalı", "Fransız", "Belçikalı", "Alman"], correct: 2 },
      { id: "ft11", imageUrl: W("Kylian_Mbapp%C3%A9_2018.jpg"), question: "Bu futbolcunun milliyeti nedir?", options: ["Belçika", "Fransa", "Senegal", "Fildişi Sahili"], correct: 1 },
      { id: "ft12", imageUrl: W("Luka_Modri%C4%87_2019_%28cropped%29.jpg"), question: "Bu futbolcunun milliyeti nedir?", options: ["Sırp", "Boşnak", "Hırvat", "Sloven"], correct: 2 },
      { id: "ft13", imageUrl: W("Mohamed_Salah_2017.jpg"), question: "Bu futbolcu hangi kulüpte oynar?", options: ["Arsenal", "Chelsea", "Liverpool", "Tottenham"], correct: 2 },
      { id: "ft14", imageUrl: W("Cristiano_Ronaldo_2018.jpg"), question: "Bu futbolcu kariyerinde kaç kez Ballon d'Or kazandı?", options: ["3", "4", "5", "6"], correct: 2 },
      { id: "ft15", imageUrl: W("Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg"), question: "Bu futbolcu hangi ülkenin milli takımında oynar?", options: ["Brezilya", "Arjantin", "Uruguay", "Kolombiya"], correct: 1 },
      { id: "ft16", imageUrl: W("Luka_Modri%C4%87_2019_%28cropped%29.jpg"), question: "Bu futbolcu hangi kulübün efsanesidir?", options: ["FC Barcelona", "Real Madrid", "Atletico Madrid", "Valencia"], correct: 1 },
      { id: "ft17", imageUrl: W("Kylian_Mbapp%C3%A9_2018.jpg"), question: "Bu futbolcu hangi kulüpte yıldızlaştı?", options: ["Olympique Lyon", "AS Monaco", "PSG", "Nice"], correct: 1 },
      { id: "ft18", imageUrl: W("Kevin_De_Bruyne.jpg"), question: "Bu futbolcu hangi kulüpte oynamaktadır?", options: ["Chelsea", "Arsenal", "Manchester City", "Tottenham"], correct: 2 },
      { id: "ft19", imageUrl: W("Cristiano_Ronaldo_2018.jpg"), question: "Bu futbolcu hangi ülkede doğmuştur?", options: ["Portekiz", "Brezilya", "İspanya", "Angola"], correct: 0 },
      { id: "ft20", imageUrl: W("Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg"), question: "Bu futbolcu 2022 Dünya Kupası'nı hangi ülkeyle kazandı?", options: ["Brezilya", "Fransa", "Arjantin", "Hırvatistan"], correct: 2 },
      { id: "ft21", imageUrl: W("Mohamed_Salah_2018.jpg"), question: "Bu futbolcu hangi ülkedendir?", options: ["Nijerya", "Fas", "Mısır", "Senegal"], correct: 2 },
      { id: "ft22", imageUrl: W("Kylian_Mbapp%C3%A9_2018.jpg"), question: "Bu futbolcu 2018'de kaç yaşında Dünya Kupası kazandı?", options: ["17", "18", "19", "20"], correct: 2 },
      { id: "ft23", imageUrl: W("Neymar_Brazil_vs_Croatia.jpg"), question: "Bu futbolcu kimdir?", options: ["Rodrygo", "Neymar", "Vinicius Jr.", "Gabriel Jesus"], correct: 1 },
      { id: "ft24", imageUrl: W("Neymar_Brazil_vs_Croatia.jpg"), question: "Bu futbolcunun milliyeti nedir?", options: ["Arjantin", "Brezilya", "Kolombiya", "Uruguay"], correct: 1 },
      { id: "ft25", imageUrl: W("Mohamed_Salah_2017.jpg"), question: "Mohamed Salah hangi ülkeyi temsil eder?", options: ["Tunus", "Cezayir", "Mısır", "Libya"], correct: 2 },
      { id: "ft26", imageUrl: W("Cristiano_Ronaldo_2018.jpg"), question: "Ronaldo'nun en çok gol attığı kulüp hangisidir?", options: ["Manchester United", "Juventus", "Real Madrid", "Al Nassr"], correct: 2 },
    ],
  },

  // ─────────────────────────────── TABLOLAR ────────────────────────────────
  {
    id: "tablolar",
    name: "Ünlü Tablolar",
    emoji: "🎨",
    color: "#a855f7",
    questions: [
      { id: "tb1",  imageUrl: W("Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Son Akşam Yemeği", "Mona Lisa", "Yıldızlı Gece", "Çığlık"], correct: 1 },
      { id: "tb2",  imageUrl: W("Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Mona Lisa", "Çığlık", "Yıldızlı Gece", "Son Akşam Yemeği"], correct: 2 },
      { id: "tb3",  imageUrl: W("The_Scream.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Yıldızlı Gece", "Guernica", "Çığlık", "Mona Lisa"], correct: 2 },
      { id: "tb4",  imageUrl: W("Girl_with_a_Pearl_Earring.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Mona Lisa", "İnci Küpeli Kız", "Venüs'ün Doğuşu", "Kahve İçen Kadın"], correct: 1 },
      { id: "tb5",  imageUrl: W("Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Son Akşam Yemeği", "Azizlerin Bahçesi", "Âdem'in Yaratılışı", "Sistina Şapeli"], correct: 2 },
      { id: "tb6",  imageUrl: W("Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"), question: "Mona Lisa'yı kim yapmıştır?", options: ["Michelangelo", "Van Gogh", "Leonardo da Vinci", "Raphael"], correct: 2 },
      { id: "tb7",  imageUrl: W("Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"), question: "Yıldızlı Gece'yi kim yapmıştır?", options: ["Claude Monet", "Salvador Dali", "Vincent van Gogh", "Pablo Picasso"], correct: 2 },
      { id: "tb8",  imageUrl: W("The_Scream.jpg"), question: "Çığlık tablosunu kim yapmıştır?", options: ["Henri Matisse", "Edvard Munch", "Paul Gauguin", "Paul Cézanne"], correct: 1 },
      { id: "tb9",  imageUrl: W("Girl_with_a_Pearl_Earring.jpg"), question: "İnci Küpeli Kız'ı kim yapmıştır?", options: ["Rembrandt", "Rubens", "Johannes Vermeer", "Frans Hals"], correct: 2 },
      { id: "tb10", imageUrl: W("Guernica.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Yıldızlı Gece", "Guernica", "Çığlık", "Hafıza Azmi"], correct: 1 },
      { id: "tb11", imageUrl: W("Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Nilüferler", "Gündoğumu", "Haystacks", "Rouen Katedrali"], correct: 0 },
      { id: "tb12", imageUrl: W("Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Mona Lisa", "İnci Küpeli Kız", "Venüs'ün Doğuşu", "Primavera"], correct: 2 },
      { id: "tb13", imageUrl: W("The_persistence_of_memory.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Belleğin Azmi", "Guernica", "Yıldızlı Gece", "Çığlık"], correct: 0 },
      { id: "tb14", imageUrl: W("The_persistence_of_memory.jpg"), question: "Belleğin Azmi tablosunu kim yapmıştır?", options: ["Pablo Picasso", "Salvador Dali", "René Magritte", "Max Ernst"], correct: 1 },
      { id: "tb15", imageUrl: W("Rembrandt_-_The_Night_Watch_-_HD.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Gece Bekçileri", "Anatomist", "Yahudi Gelinin", "Doktora Ders"], correct: 0 },
      { id: "tb16", imageUrl: W("Rembrandt_-_The_Night_Watch_-_HD.jpg"), question: "Gece Bekçileri'ni kim yapmıştır?", options: ["Vermeer", "Rubens", "Rembrandt", "Hals"], correct: 2 },
      { id: "tb17", imageUrl: W("American_Gothic.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Christina'nın Dünyası", "Amerikan Gotiği", "Nighthawks", "Solitude"], correct: 1 },
      { id: "tb18", imageUrl: W("Van_Gogh_-_Sunflowers.jpg"), question: "Bu ünlü tablo hangisidir?", options: ["Gül Bahçesi", "Ayçiçekleri", "Nilüferler", "Iris'ler"], correct: 1 },
      { id: "tb19", imageUrl: W("Van_Gogh_-_Sunflowers.jpg"), question: "Ayçiçekleri tablosunu kim yapmıştır?", options: ["Monet", "Renoir", "Van Gogh", "Gauguin"], correct: 2 },
      { id: "tb20", imageUrl: W("Guernica.jpg"), question: "Guernica tablosunu kim yapmıştır?", options: ["Salvador Dali", "Pablo Picasso", "Joan Miró", "Juan Gris"], correct: 1 },
      { id: "tb21", imageUrl: W("Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg"), question: "Âdem'in Yaratılışı hangi binada bulunmaktadır?", options: ["Louvre", "Uffizi", "Sistina Şapeli", "Vatikan Müzesi"], correct: 2 },
      { id: "tb22", imageUrl: W("Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg"), question: "Nilüferler tablosunu kim yapmıştır?", options: ["Auguste Renoir", "Claude Monet", "Edgar Degas", "Paul Cézanne"], correct: 1 },
      { id: "tb23", imageUrl: W("Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg"), question: "Venüs'ün Doğuşu'nu kim yapmıştır?", options: ["Raphael", "Titian", "Sandro Botticelli", "Leonardo da Vinci"], correct: 2 },
      { id: "tb24", imageUrl: W("Girl_with_a_Pearl_Earring.jpg"), question: "İnci Küpeli Kız hangi müzede bulunur?", options: ["Louvre", "Mauritshuis", "Rijksmuseum", "Hermitage"], correct: 1 },
      { id: "tb25", imageUrl: W("Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"), question: "Mona Lisa hangi müzede bulunur?", options: ["British Museum", "Uffizi", "Louvre", "MoMA"], correct: 2 },
      { id: "tb26", imageUrl: W("The_Scream.jpg"), question: "Çığlık hangi ülke sanatçısına aittir?", options: ["İsveç", "Danimarka", "Finlandiya", "Norveç"], correct: 3 },
      { id: "tb27", imageUrl: W("Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"), question: "Van Gogh hangi ülkelidir?", options: ["Fransa", "Belçika", "Hollanda", "Almanya"], correct: 2 },
      { id: "tb28", imageUrl: W("Guernica.jpg"), question: "Guernica hangi olayı tasvir eder?", options: ["I. Dünya Savaşı", "İspanya İç Savaşı", "II. Dünya Savaşı", "Fransız Devrimi"], correct: 1 },
      { id: "tb29", imageUrl: W("American_Gothic.jpg"), question: "Amerikan Gotiği'ni kim yapmıştır?", options: ["Edward Hopper", "Grant Wood", "Andrew Wyeth", "Thomas Eakins"], correct: 1 },
      { id: "tb30", imageUrl: W("The_persistence_of_memory.jpg"), question: "Belleğin Azmi hangi akımı temsil eder?", options: ["Empresyonizm", "Sürrealizm", "Kübizm", "Ekspresyonizm"], correct: 1 },
    ],
  },

  // ────────────────────────────── DÜNYA MUTFAĞI ────────────────────────────
  {
    id: "mutfak",
    name: "Dünya Mutfağı",
    emoji: "🍽️",
    color: "#f97316",
    questions: [
      { id: "mt1",  imageUrl: W("Eq_it-na_pizza-margherita_sep2005_sml.jpg"), question: "Bu yemek nedir?", options: ["Calzone", "Lahmacun", "Pizza", "Pide"], correct: 2 },
      { id: "mt2",  imageUrl: W("RawRoll_Maki.jpg"), question: "Bu yemek nedir?", options: ["Dim Sum", "Sushi", "Dumplings", "Spring Roll"], correct: 1 },
      { id: "mt3",  imageUrl: W("A_small_cup_of_coffee.JPG"), question: "Bu içecek nedir?", options: ["Espresso", "Americano", "Latte", "Kahve"], correct: 3 },
      { id: "mt4",  imageUrl: W("Spaghetti_bolognese_%28hozinja%29.jpg"), question: "Bu yemek nedir?", options: ["Lazanya", "Makarna", "Risotto", "Penne"], correct: 1 },
      { id: "mt5",  imageUrl: W("Hamburger.jpg"), question: "Bu yemek nedir?", options: ["Sandviç", "Hamburger", "Taco", "Wrap"], correct: 1 },
      { id: "mt6",  imageUrl: W("Ramen.jpg"), question: "Bu yemek nedir?", options: ["Pho", "Ramen", "Udon", "Pad Thai"], correct: 1 },
      { id: "mt7",  imageUrl: W("Hapus_Mango.jpg"), question: "Bu meyve nedir?", options: ["Papaya", "Mango", "Guava", "Jackfruit"], correct: 1 },
      { id: "mt8",  imageUrl: W("Big_Mac_hamburger.jpg"), question: "Bu ünlü burger hangisidir?", options: ["Whopper", "Big Mac", "Quarter Pounder", "Double Cheeseburger"], correct: 1 },
      { id: "mt9",  imageUrl: W("Shawarma.jpg"), question: "Bu yemek nedir?", options: ["Kebap", "Dürüm", "Şavarma", "Döner"], correct: 2 },
      { id: "mt10", imageUrl: W("Chocolate_fondue.jpg"), question: "Bu tatlı hangisidir?", options: ["Çikolatalı Fondue", "Tiramisu", "Brownies", "Sufle"], correct: 0 },
      { id: "mt11", imageUrl: W("Pad_thai.jpg"), question: "Bu yemek nedir?", options: ["Phad See Ew", "Tom Yum", "Pad Thai", "Massaman Körisi"], correct: 2 },
      { id: "mt12", imageUrl: W("Gelato_artigianale.jpg"), question: "Bu İtalyan tatlısı nedir?", options: ["Dondurma", "Sorbeto", "Gelato", "Semifreddo"], correct: 2 },
      { id: "mt13", imageUrl: W("Chocolate_cake.jpg"), question: "Bu tatlı nedir?", options: ["Brownie", "Muffin", "Çikolatalı Kek", "Sufle"], correct: 2 },
      { id: "mt14", imageUrl: W("Pizza-3007395.jpg"), question: "Pizza hangi ülkenin yemeğidir?", options: ["Fransa", "İspanya", "İtalya", "Yunanistan"], correct: 2 },
      { id: "mt15", imageUrl: W("Tiramisu_-_stonesoup.jpg"), question: "Bu İtalyan tatlısı nedir?", options: ["Panna Cotta", "Cannoli", "Tiramisu", "Zuppa Inglese"], correct: 2 },
      { id: "mt16", imageUrl: W("Turkish_Baklava.jpg"), question: "Bu tatlı nedir?", options: ["Kadayıf", "Künefe", "Baklava", "Şekerpare"], correct: 2 },
      { id: "mt17", imageUrl: W("Tacos_de_carnitas%2C_Mexico_City.jpg"), question: "Bu yemek nedir?", options: ["Burrito", "Quesadilla", "Enchilada", "Taco"], correct: 3 },
      { id: "mt18", imageUrl: W("Tom_yum_kung.jpg"), question: "Bu yemek nedir?", options: ["Pho", "Miso Çorbası", "Tom Yum", "Hotpot"], correct: 2 },
      { id: "mt19", imageUrl: W("Croissant_l%C3%A9ger.jpg"), question: "Bu fırın ürünü nedir?", options: ["Baget", "Brioche", "Kruvasan", "Pain au chocolat"], correct: 2 },
      { id: "mt20", imageUrl: W("Biryani_dish.jpg"), question: "Bu Güney Asya yemeği nedir?", options: ["Pilav", "Biryani", "Fried Rice", "Pulao"], correct: 1 },
      { id: "mt21", imageUrl: W("Falafel_fried_1.jpg"), question: "Bu Orta Doğu yemeği nedir?", options: ["Humus", "Dolma", "Falafel", "Muhammar"], correct: 2 },
      { id: "mt22", imageUrl: W("Paella_01.jpg"), question: "Bu yemek nedir?", options: ["Risotto", "Pilav", "Paella", "Couscous"], correct: 2 },
      { id: "mt23", imageUrl: W("Hummus_garnished.jpg"), question: "Bu Orta Doğu yemeği nedir?", options: ["Baba Ganuş", "Tahin", "Humus", "Mutabbal"], correct: 2 },
      { id: "mt24", imageUrl: W("Sushi_platter.jpg"), question: "Sushi hangi ülkenin mutfağına aittir?", options: ["Çin", "Kore", "Japonya", "Tayland"], correct: 2 },
      { id: "mt25", imageUrl: W("Ramen.jpg"), question: "Ramen hangi ülkenin yemeğidir?", options: ["Çin", "Kore", "Japonya", "Vietnam"], correct: 2 },
      { id: "mt26", imageUrl: W("Eq_it-na_pizza-margherita_sep2005_sml.jpg"), question: "Bu pizza çeşidi hangisidir?", options: ["Pepperoni", "Margherita", "BBQ Chicken", "Quattro Formaggi"], correct: 1 },
      { id: "mt27", imageUrl: W("Pho_bo.jpg"), question: "Bu Vietnam yemeği nedir?", options: ["Ramen", "Udon", "Pho", "Laksa"], correct: 2 },
      { id: "mt28", imageUrl: W("Moussaka_-_stonesoup.jpg"), question: "Bu Yunan yemeği nedir?", options: ["Pastitsio", "Musaka", "Spanakopita", "Dolmades"], correct: 1 },
      { id: "mt29", imageUrl: W("Korean_Kimchi.jpg"), question: "Bu Kore yemeği nedir?", options: ["Banchan", "Bibimbap", "Kimchi", "Japchae"], correct: 2 },
      { id: "mt30", imageUrl: W("Churros_with_dipping_sauce.jpg"), question: "Bu İspanyol tatlısı nedir?", options: ["Empanada", "Churros", "Alfajores", "Polvorón"], correct: 1 },
      { id: "mt31", imageUrl: W("Waffles_with_strawberries.jpg"), question: "Bu kahvaltı yemeği nedir?", options: ["Pancake", "Krep", "Gözleme", "Waffle"], correct: 3 },
      { id: "mt32", imageUrl: W("Dim_sum_by_Wikipedia_user_Mk2010.jpg"), question: "Bu Çin yemeği nedir?", options: ["Gyoza", "Bao", "Dim Sum", "Wontons"], correct: 2 },
    ],
  },

  // ──────────────────────────────── ÜNLÜLER ────────────────────────────────
  {
    id: "unluler",
    name: "Ünlüler",
    emoji: "🌟",
    color: "#ec4899",
    questions: [
      { id: "un1",  imageUrl: W("Albert_Einstein_Head.jpg"), question: "Bu ünlü bilim insanı kimdir?", options: ["Isaac Newton", "Nikola Tesla", "Albert Einstein", "Stephen Hawking"], correct: 2 },
      { id: "un2",  imageUrl: W("Mustafa_Kemal_Ataturk.jpg"), question: "Bu tarihi lider kimdir?", options: ["İsmet İnönü", "Mustafa Kemal Atatürk", "Enver Paşa", "Fevzi Çakmak"], correct: 1 },
      { id: "un3",  imageUrl: W("Barack_Obama.jpg"), question: "Bu devlet adamı kimdir?", options: ["Joe Biden", "Barack Obama", "George W. Bush", "Bill Clinton"], correct: 1 },
      { id: "un4",  imageUrl: W("Elon_Musk_Royal_Society.jpg"), question: "Bu ünlü girişimci kimdir?", options: ["Jeff Bezos", "Bill Gates", "Elon Musk", "Tim Cook"], correct: 2 },
      { id: "un5",  imageUrl: W("Beethoven.jpg"), question: "Bu ünlü besteci kimdir?", options: ["Mozart", "Bach", "Beethoven", "Chopin"], correct: 2 },
      { id: "un6",  imageUrl: W("Leonardo_da_Vinci_-_presumed_self-portrait_-_WGA12798.jpg"), question: "Bu ünlü sanatçı kimdir?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Caravaggio"], correct: 2 },
      { id: "un7",  imageUrl: W("Marie_Curie_%28Nobel-Chem%29.jpg"), question: "Bu ünlü bilim insanı kimdir?", options: ["Florence Nightingale", "Rosalind Franklin", "Marie Curie", "Ada Lovelace"], correct: 2 },
      { id: "un8",  imageUrl: W("Charles_Darwin_seated_crop.jpg"), question: "Bu ünlü bilim insanı kimdir?", options: ["Isaac Newton", "Charles Darwin", "Gregor Mendel", "Louis Pasteur"], correct: 1 },
      { id: "un9",  imageUrl: W("Barack_Obama.jpg"), question: "Bu kişi hangi ülkenin başkanıydı?", options: ["Fransa", "İngiltere", "Amerika Birleşik Devletleri", "Kanada"], correct: 2 },
      { id: "un10", imageUrl: W("Elon_Musk_Royal_Society.jpg"), question: "Bu kişinin kurduğu şirket hangisidir?", options: ["Amazon", "Apple", "Tesla", "Meta"], correct: 2 },
      { id: "un11", imageUrl: W("Albert_Einstein_Head.jpg"), question: "Bu kişi hangi teorisiyle ünlüdür?", options: ["Yerçekimi", "Evrim", "Görelilik", "Kuantum"], correct: 2 },
      { id: "un12", imageUrl: W("Beethoven.jpg"), question: "Bu besteci hangi millettendir?", options: ["Avusturyalı", "Alman", "Fransız", "İtalyan"], correct: 1 },
      { id: "un13", imageUrl: W("Stephen_Hawking.StarChild.jpg"), question: "Bu ünlü bilim insanı kimdir?", options: ["Carl Sagan", "Richard Feynman", "Stephen Hawking", "Michio Kaku"], correct: 2 },
      { id: "un14", imageUrl: W("Abraham_Lincoln_head_on_shoulders_photo_portrait.jpg"), question: "Bu tarihi lider kimdir?", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Theodore Roosevelt"], correct: 1 },
      { id: "un15", imageUrl: W("Nelson_Mandela.jpg"), question: "Bu tarihi lider kimdir?", options: ["Desmond Tutu", "Nelson Mandela", "Kofi Annan", "Jomo Kenyatta"], correct: 1 },
      { id: "un16", imageUrl: W("Napoleon_Bonaparte.jpg"), question: "Bu tarihi lider kimdir?", options: ["Louis XVI", "Napolyon Bonapart", "Charles de Gaulle", "Richelieu"], correct: 1 },
      { id: "un17", imageUrl: W("Marie_Curie_%28Nobel-Chem%29.jpg"), question: "Marie Curie hangi ülkeden gelmektedir?", options: ["Fransa", "Almanya", "Polonya", "Rusya"], correct: 2 },
      { id: "un18", imageUrl: W("Charles_Darwin_seated_crop.jpg"), question: "Charles Darwin hangi teorisiyle ünlüdür?", options: ["Yerçekimi", "Görelilik", "Evrim Teorisi", "Termodinamik"], correct: 2 },
      { id: "un19", imageUrl: W("Stephen_Hawking.StarChild.jpg"), question: "Stephen Hawking neyin teorisi üzerinde çalışmıştır?", options: ["Kuantum Mekaniği", "Kara Delikler", "Big Bang", "Genetik"], correct: 1 },
      { id: "un20", imageUrl: W("Abraham_Lincoln_head_on_shoulders_photo_portrait.jpg"), question: "Lincoln hangi savaşla anılır?", options: ["Birinci Dünya Savaşı", "İkinci Dünya Savaşı", "Amerikan İç Savaşı", "Soğuk Savaş"], correct: 2 },
      { id: "un21", imageUrl: W("Nelson_Mandela.jpg"), question: "Nelson Mandela'nın ülkesi neresidir?", options: ["Kenya", "Zimbabve", "Namibya", "Güney Afrika"], correct: 3 },
      { id: "un22", imageUrl: W("Napoleon_Bonaparte.jpg"), question: "Napolyon hangi ülkenin imparatoru olmuştur?", options: ["İtalya", "Fransa", "İspanya", "Hollanda"], correct: 1 },
      { id: "un23", imageUrl: W("Tesla_circa_1890.jpg"), question: "Bu ünlü mucit kimdir?", options: ["Thomas Edison", "Nikola Tesla", "Alexander Bell", "Guglielmo Marconi"], correct: 1 },
      { id: "un24", imageUrl: W("Isaac_Newton_%28Bolton%2C_Hannah%29.jpg"), question: "Bu ünlü bilim insanı kimdir?", options: ["Galileo Galilei", "Isaac Newton", "Johannes Kepler", "Tycho Brahe"], correct: 1 },
      { id: "un25", imageUrl: W("Mahatma-Gandhi.jpg"), question: "Bu tarihi lider kimdir?", options: ["Jawaharlal Nehru", "Subhas Bose", "Bal Gangadhar Tilak", "Mahatma Gandhi"], correct: 3 },
      { id: "un26", imageUrl: W("Winston_Churchill.jpg"), question: "Bu devlet adamı kimdir?", options: ["Neville Chamberlain", "Anthony Eden", "Winston Churchill", "Clement Attlee"], correct: 2 },
      { id: "un27", imageUrl: W("Tesla_circa_1890.jpg"), question: "Nikola Tesla hangi buluşuyla ünlüdür?", options: ["Telefon", "AC Elektrik", "Ampul", "Radyo Telsizi"], correct: 1 },
      { id: "un28", imageUrl: W("Isaac_Newton_%28Bolton%2C_Hannah%29.jpg"), question: "Newton hangi kanunla ünlüdür?", options: ["Termodinamik", "Yerçekimi Yasası", "Görelilik", "Kuantum"], correct: 1 },
      { id: "un29", imageUrl: W("Mustafa_Kemal_Ataturk.jpg"), question: "Atatürk hangi yıl Türkiye Cumhuriyeti'ni kurdu?", options: ["1919", "1921", "1923", "1925"], correct: 2 },
      { id: "un30", imageUrl: W("Barack_Obama.jpg"), question: "Obama Amerika'nın kaçıncı başkanıydı?", options: ["42", "43", "44", "45"], correct: 2 },
      { id: "un31", imageUrl: W("Mahatma-Gandhi.jpg"), question: "Gandhi hangi ülkenin bağımsızlık mücadelesini yürüttü?", options: ["Pakistan", "Hindistan", "Bangladeş", "Sri Lanka"], correct: 1 },
      { id: "un32", imageUrl: W("Winston_Churchill.jpg"), question: "Churchill hangi savaş döneminde ön plana çıktı?", options: ["I. Dünya Savaşı", "II. Dünya Savaşı", "Kore Savaşı", "Soğuk Savaş"], correct: 1 },
    ],
  },

  // ──────────────────────────────── SPORCULAR ───────────────────────────────
  {
    id: "sporcular",
    name: "Sporcular",
    emoji: "🏆",
    color: "#f43f5e",
    questions: [
      { id: "sp1",  imageUrl: W("Usain_Bolt_Berlin_2009.jpg"), question: "Bu sporcu kimdir?", options: ["Asafa Powell", "Yohan Blake", "Usain Bolt", "Justin Gatlin"], correct: 2 },
      { id: "sp2",  imageUrl: W("Muhammad_Ali_NYWTS.jpg"), question: "Bu sporcu kimdir?", options: ["Joe Frazier", "George Foreman", "Mike Tyson", "Muhammad Ali"], correct: 3 },
      { id: "sp3",  imageUrl: W("Roger_Federer_%282%29.jpg"), question: "Bu sporcu kimdir?", options: ["Rafael Nadal", "Novak Djokovic", "Roger Federer", "Pete Sampras"], correct: 2 },
      { id: "sp4",  imageUrl: W("Serena_Williams_at_the_2013_US_Open.jpg"), question: "Bu sporcu kimdir?", options: ["Venus Williams", "Maria Sharapova", "Steffi Graf", "Serena Williams"], correct: 3 },
      { id: "sp5",  imageUrl: W("Michael_Phelps.jpg"), question: "Bu sporcu kimdir?", options: ["Ryan Lochte", "Ian Thorpe", "Mark Spitz", "Michael Phelps"], correct: 3 },
      { id: "sp6",  imageUrl: W("LeBron_James_%282%29.jpg"), question: "Bu sporcu kimdir?", options: ["Kobe Bryant", "Michael Jordan", "Kevin Durant", "LeBron James"], correct: 3 },
      { id: "sp7",  imageUrl: W("Usain_Bolt_Berlin_2009.jpg"), question: "Usain Bolt hangi ülkeyi temsil eder?", options: ["Trinidad", "Bahama", "Jamaika", "Barbados"], correct: 2 },
      { id: "sp8",  imageUrl: W("Muhammad_Ali_NYWTS.jpg"), question: "Bu sporcu hangi branşta ünlüdür?", options: ["Güreş", "Boks", "Judo", "Karate"], correct: 1 },
      { id: "sp9",  imageUrl: W("Roger_Federer_%282%29.jpg"), question: "Roger Federer hangi ülkedendir?", options: ["Almanya", "Avusturya", "İsviçre", "İsveç"], correct: 2 },
      { id: "sp10", imageUrl: W("Serena_Williams_at_the_2013_US_Open.jpg"), question: "Serena Williams hangi sporda aktiftir?", options: ["Squash", "Badminton", "Masa Tenisi", "Tenis"], correct: 3 },
      { id: "sp11", imageUrl: W("Michael_Phelps.jpg"), question: "Michael Phelps hangi sporda rekortmendir?", options: ["Atletizm", "Yüzme", "Triatlon", "Dalış"], correct: 1 },
      { id: "sp12", imageUrl: W("LeBron_James_%282%29.jpg"), question: "LeBron James hangi sporu yapar?", options: ["Beyzbol", "Amerikan Futbolu", "Basketbol", "Hokey"], correct: 2 },
      { id: "sp13", imageUrl: W("Tiger_Woods.jpg"), question: "Bu sporcu kimdir?", options: ["Phil Mickelson", "Tiger Woods", "Rory McIlroy", "Jack Nicklaus"], correct: 1 },
      { id: "sp14", imageUrl: W("Tiger_Woods.jpg"), question: "Tiger Woods hangi sporda ünlüdür?", options: ["Tenis", "Golf", "Polo", "Beyzbol"], correct: 1 },
      { id: "sp15", imageUrl: W("Usain_Bolt_Berlin_2009.jpg"), question: "Usain Bolt'un uzmanlık dalı nedir?", options: ["Maraton", "Engelli Koşu", "Sprint", "Yürüyüş"], correct: 2 },
      { id: "sp16", imageUrl: W("LeBron_James_%282%29.jpg"), question: "Bu oyuncu hangi NBA takımıyla özdeşleşmiştir?", options: ["Chicago Bulls", "Los Angeles Lakers", "Golden State Warriors", "Boston Celtics"], correct: 1 },
      { id: "sp17", imageUrl: W("Roger_Federer_%282%29.jpg"), question: "Federer en çok hangi Grand Slam'ı kazanmıştır?", options: ["Roland Garros", "Australian Open", "US Open", "Wimbledon"], correct: 3 },
      { id: "sp18", imageUrl: W("Serena_Williams_at_the_2013_US_Open.jpg"), question: "Serena Williams hangi ülkedendir?", options: ["Fransa", "İngiltere", "Avustralya", "Amerika Birleşik Devletleri"], correct: 3 },
      { id: "sp19", imageUrl: W("Michael_Phelps.jpg"), question: "Phelps kaç olimpiyat altın madalyası kazanmıştır?", options: ["15", "18", "23", "28"], correct: 2 },
      { id: "sp20", imageUrl: W("Muhammad_Ali_NYWTS.jpg"), question: "Ali'nin gerçek adı nedir?", options: ["Roy Jones Jr.", "Cassius Clay", "Floyd Patterson", "Sonny Liston"], correct: 1 },
      { id: "sp21", imageUrl: W("Tiger_Woods.jpg"), question: "Tiger Woods kaç Major kazanmıştır?", options: ["10", "12", "15", "18"], correct: 2 },
      { id: "sp22", imageUrl: W("Usain_Bolt_Berlin_2009.jpg"), question: "Bolt'un 100m dünya rekoru kaçtır?", options: ["9.58 sn", "9.63 sn", "9.69 sn", "9.72 sn"], correct: 0 },
    ],
  },

  // ──────────────────────────────── COĞRAFYA ────────────────────────────────
  {
    id: "cografya",
    name: "Coğrafya",
    emoji: "🌍",
    color: "#0ea5e9",
    questions: [
      { id: "cg1",  imageUrl: W("Mount_Everest_as_seen_from_Drukair2_PLW_edit.jpg"), question: "Bu dağ hangisidir?", options: ["K2", "Kangchenjunga", "Everest", "Lhotse"], correct: 2 },
      { id: "cg2",  imageUrl: W("Victoria_Falls_-_Zimbabwe_%28August_2009%29.jpg"), question: "Bu şelale nedir?", options: ["Niagara Şelalesi", "Angel Şelalesi", "Victoria Şelalesi", "Iguazu Şelalesi"], correct: 2 },
      { id: "cg3",  imageUrl: W("Niagara_Falls.jpg"), question: "Bu şelale hangi ülkeler arasındadır?", options: ["ABD - Meksika", "ABD - Kanada", "Arjantin - Brezilya", "Zimbabwe - Zambiya"], correct: 1 },
      { id: "cg4",  imageUrl: W("Grand_Canyon_skywalk.jpg"), question: "Bu kanyon nerededir?", options: ["Kanada", "Meksika", "Avustralya", "Amerika Birleşik Devletleri"], correct: 3 },
      { id: "cg5",  imageUrl: W("Sahara_desert.jpg"), question: "Bu çöl hangisidir?", options: ["Gobi", "Atacama", "Sahara", "Namib"], correct: 2 },
      { id: "cg6",  imageUrl: W("Aurora_Borealis.jpg"), question: "Bu doğa olayı nedir?", options: ["Meteor Yağmuru", "Güneş Halkası", "Kuzey Işıkları (Aurora)", "Şimşek Fırtınası"], correct: 2 },
      { id: "cg7",  imageUrl: W("Great_Barrier_Reef.jpg"), question: "Bu doğal oluşum nedir?", options: ["Maldivler Mercan Adaları", "Büyük Set Resifi", "Kızıldeniz Mercanları", "Meksika Körfezi"], correct: 1 },
      { id: "cg8",  imageUrl: W("Amazon_River_near_Manaus.jpg"), question: "Bu nehir hangisidir?", options: ["Nil", "Mississipi", "Amazon", "Orinoco"], correct: 2 },
      { id: "cg9",  imageUrl: W("Mount_Everest_as_seen_from_Drukair2_PLW_edit.jpg"), question: "Everest hangi ülkede bulunur?", options: ["Hindistan", "Pakistan", "Nepal/Tibet", "Bhutan"], correct: 2 },
      { id: "cg10", imageUrl: W("Sahara_desert.jpg"), question: "Sahra Çölü hangi kıtadadır?", options: ["Asya", "Güney Amerika", "Afrika", "Avustralya"], correct: 2 },
      { id: "cg11", imageUrl: W("Victoria_Falls_-_Zimbabwe_%28August_2009%29.jpg"), question: "Victoria Şelalesi hangi kıtadadır?", options: ["Güney Amerika", "Asya", "Afrika", "Avustralya"], correct: 2 },
      { id: "cg12", imageUrl: W("Great_Barrier_Reef.jpg"), question: "Büyük Set Resifi hangi ülkenin kıyısındadır?", options: ["Yeni Zelanda", "Endonezya", "Papua Yeni Gine", "Avustralya"], correct: 3 },
      { id: "cg13", imageUrl: W("Pamukkale.jpg"), question: "Bu ünlü doğal oluşum Türkiye'de neredededir?", options: ["Kapadokya", "Pamukkale", "Efes", "Dalyan"], correct: 1 },
      { id: "cg14", imageUrl: W("Cappadocia_Aerial_Pano_May_2012.jpg"), question: "Bu eşsiz coğrafya nerededir?", options: ["İran", "Suriye", "Türkiye", "Yunanistan"], correct: 2 },
      { id: "cg15", imageUrl: W("Aurora_Borealis.jpg"), question: "Kuzey Işıkları en çok nerede görülür?", options: ["Kanada", "Norveç", "İzlanda", "Hepsi doğru"], correct: 3 },
      { id: "cg16", imageUrl: W("Amazon_River_near_Manaus.jpg"), question: "Amazon Nehri hangi ülkededir?", options: ["Arjantin", "Kolombiya", "Brezilya", "Peru"], correct: 2 },
      { id: "cg17", imageUrl: W("Grand_Canyon_skywalk.jpg"), question: "Grand Canyon hangi ABD eyaletindedir?", options: ["Colorado", "Utah", "Arizona", "Nevada"], correct: 2 },
      { id: "cg18", imageUrl: W("Niagara_Falls.jpg"), question: "Niagara Şelalesi hangi kıtadadır?", options: ["Güney Amerika", "Kuzey Amerika", "Avrupa", "Afrika"], correct: 1 },
      { id: "cg19", imageUrl: W("Kilimanjaro.jpg"), question: "Bu dağ nerededir?", options: ["Kenya", "Tanzanya", "Etyopya", "Mozambik"], correct: 1 },
      { id: "cg20", imageUrl: W("Iguazu_Falls.jpg"), question: "Bu şelale nerededir?", options: ["Brezilya/Arjantin", "Venezüela", "Kolombiya", "Peru"], correct: 0 },
      { id: "cg21", imageUrl: W("Dead_Sea_by_David_Shankbone.jpg"), question: "Bu yer neresidir?", options: ["Van Gölü", "Ölü Deniz", "Tuz Gölü", "Aral Denizi"], correct: 1 },
      { id: "cg22", imageUrl: W("Gobi_desert.jpg"), question: "Bu çöl hangisidir?", options: ["Sahara", "Atacama", "Gobi", "Taklamakan"], correct: 2 },
    ],
  },

  // ────────────────────────────── MÜZİSYENLER ─────────────────────────────
  {
    id: "muzisyenler",
    name: "Müzisyenler",
    emoji: "🎵",
    color: "#8b5cf6",
    questions: [
      { id: "mz1",  imageUrl: W("Michael_Jackson_1984.jpg"), question: "Bu müzisyen kimdir?", options: ["Prince", "Michael Jackson", "Stevie Wonder", "James Brown"], correct: 1 },
      { id: "mz2",  imageUrl: W("Elvis_Presley_promoting_Jailhouse_Rock.jpg"), question: "Bu müzisyen kimdir?", options: ["Chuck Berry", "Little Richard", "Elvis Presley", "Jerry Lee Lewis"], correct: 2 },
      { id: "mz3",  imageUrl: W("Bob-Marley.jpg"), question: "Bu müzisyen kimdir?", options: ["Jimmy Cliff", "Bob Marley", "Peter Tosh", "Burning Spear"], correct: 1 },
      { id: "mz4",  imageUrl: W("Wolfgang-amadeus-mozart_1.jpg"), question: "Bu ünlü besteci kimdir?", options: ["Haydn", "Salieri", "Mozart", "Schubert"], correct: 2 },
      { id: "mz5",  imageUrl: W("Johann_Sebastian_Bach.jpg"), question: "Bu ünlü besteci kimdir?", options: ["Handel", "Vivaldi", "Bach", "Telemann"], correct: 2 },
      { id: "mz6",  imageUrl: W("Beethoven.jpg"), question: "Bu besteci hangi senfonisiyle ünlüdür?", options: ["5. Senfoni", "9. Senfoni", "3. Senfoni", "7. Senfoni"], correct: 1 },
      { id: "mz7",  imageUrl: W("Michael_Jackson_1984.jpg"), question: "Michael Jackson'ın en çok satan albümü nedir?", options: ["Thriller", "Bad", "Off the Wall", "Dangerous"], correct: 0 },
      { id: "mz8",  imageUrl: W("Elvis_Presley_promoting_Jailhouse_Rock.jpg"), question: "Elvis Presley hangi müzik türüyle ünlüdür?", options: ["Jazz", "Blues", "Rock and Roll", "Country"], correct: 2 },
      { id: "mz9",  imageUrl: W("Bob-Marley.jpg"), question: "Bob Marley hangi müzik türünün efsanesidir?", options: ["Ska", "Reggae", "Dancehall", "Calypso"], correct: 1 },
      { id: "mz10", imageUrl: W("Wolfgang-amadeus-mozart_1.jpg"), question: "Mozart hangi ülkede doğmuştur?", options: ["Almanya", "İsviçre", "Avusturya", "Çek Cumhuriyeti"], correct: 2 },
      { id: "mz11", imageUrl: W("Johann_Sebastian_Bach.jpg"), question: "Bach hangi ülkede yaşamıştır?", options: ["Avusturya", "Hollanda", "İsviçre", "Almanya"], correct: 3 },
      { id: "mz12", imageUrl: W("Freddie_Mercury.jpg"), question: "Bu müzisyen kimdir?", options: ["David Bowie", "Elton John", "Freddie Mercury", "Rod Stewart"], correct: 2 },
      { id: "mz13", imageUrl: W("Freddie_Mercury.jpg"), question: "Bu müzisyen hangi grubun solisti olmuştur?", options: ["Led Zeppelin", "The Rolling Stones", "Queen", "The Who"], correct: 2 },
      { id: "mz14", imageUrl: W("Michael_Jackson_1984.jpg"), question: "Michael Jackson hangi ülkede doğmuştur?", options: ["İngiltere", "Jamaika", "Amerika Birleşik Devletleri", "Kanada"], correct: 2 },
      { id: "mz15", imageUrl: W("Bob-Marley.jpg"), question: "Bob Marley hangi ülkede doğmuştur?", options: ["Trinidad", "Jamaika", "Barbados", "Haiti"], correct: 1 },
      { id: "mz16", imageUrl: W("Wolfgang-amadeus-mozart_1.jpg"), question: "Mozart kaç yaşında hayatını kaybetti?", options: ["25", "31", "35", "41"], correct: 2 },
      { id: "mz17", imageUrl: W("Freddie_Mercury.jpg"), question: "Queen grubunun en ünlü şarkısı nedir?", options: ["We Are The Champions", "Bohemian Rhapsody", "Don't Stop Me Now", "Radio Ga Ga"], correct: 1 },
      { id: "mz18", imageUrl: W("Elvis_Presley_promoting_Jailhouse_Rock.jpg"), question: "Elvis Presley'nin lakabı nedir?", options: ["King of Pop", "King of Rock and Roll", "Duke of Blues", "Prince of Soul"], correct: 1 },
      { id: "mz19", imageUrl: W("Johann_Sebastian_Bach.jpg"), question: "Bach hangi dönemde yaşamıştır?", options: ["Rönesans", "Barok", "Klasik", "Romantik"], correct: 1 },
      { id: "mz20", imageUrl: W("Michael_Jackson_1984.jpg"), question: "Michael Jackson'ın ayırt edici dans hareketi nedir?", options: ["Running Man", "Pop Lock", "Moonwalk", "Robot"], correct: 2 },
    ],
  },
];

export function getRandomImageQuestions(categoryId: string, count: number): ImageQuestion[] {
  const cat = IMAGE_CATEGORIES.find((c) => c.id === categoryId);
  if (!cat) return [];
  const shuffled = [...cat.questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getImageCategory(categoryId: string): ImageCategory | undefined {
  return IMAGE_CATEGORIES.find((c) => c.id === categoryId);
}
